FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["HangfireDemo.Api/HangfireDemo.Api.csproj", "HangfireDemo.Api/"]
RUN dotnet restore "HangfireDemo.Api/HangfireDemo.Api.csproj"
COPY . .
WORKDIR "/src/HangfireDemo.Api"
RUN dotnet build "HangfireDemo.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build
RUN apt-get update && apt-get install -y wget telnet iputils-ping

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "HangfireDemo.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HangfireDemo.Api.dll"]
