FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy everything
COPY ./HangfireDemo.Common/ ./HangfireDemo.Common/
COPY ./HangfireDemo.Server/ ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
RUN apt-get update && apt-get install -y wget telnet iputils-ping
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "HangfireDemo.Server.dll"]
