services:
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - hangfire-network
#    depends_on:
#      api:
#        condition: service_healthy
  
  api:
    image: warleyfs/hangfire-demo:1.0.23
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - hangfire-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthz || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
      
  mongo:
    image: mongo
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - ~/MongoDB:/data/db
    networks:
      - hangfire-network

networks:
  hangfire-network:
    driver: bridge