apiVersion: v1
kind: Service
metadata:
  name: hangfire-mongo-service
spec:
  selector:
    app: hangfire-demo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017
  type: NodePort